server.port=8082

spring.application.name=journal-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=journal_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Aniket

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true